### ISSUE TITLE
Something wrong with Tuya library used by HA

### ISSUE THREAD

**Issue by uros76** [tuya/tuya-iot-python-sdk#70]
Hi. Recently Tuya integration for HomeAssistant stopped working. Apparently, the issue is on Tuya IOT library side. See more about this here: https://github.com/home-assistant/core/issues/84935

Can someone please look into this? There are multiple HA users with Tuya integration that lost the connection with devices...

**Comment by frenck** [comment]
This is a different message than you reported in the upstream issue. The upstream issue was about not caching error properly, in this message you start with:

> Recently Tuya integration for HomeAssistant stopped working

That is generally caused by a different issue (which is not related to error catching).

For more information on that see: <https://github.com/home-assistant/core/issues/80278>

**Comment by uros76** [comment]
Thank you @frenck for pointing me into right direction. Closing this issue here
